# 站点信息
site_name: WALI_FrameWork  # 文档站点名称
site_description: A sample documentation site  # 文档站点描述
site_author: kk # 文档作者

# 导航栏
nav:
  - Home: index.md
  - 入门指南:
    - 安装指南: installation.md
    - 快速上手: quick-start.md
  - 用户指南:
    - 配置: config.md
    - 使用方法: usage.md
  - 基础知识: 
    - 变参函数和可变参数宏: basic_knowledge/ParameterMacro.md
    - 面向对象脚本语言: 
    - 状态机: basic_knowledge/fsm.md    
    - 状态机脚本语言: basic_knowledge/fsm.md        
    - 线程安全和多实例: basic_knowledge/ThreadSafetyAndFunctionReentrancy.md

  - 模块:
    - ymodem: ymodem/ymodem.md  
    - queue:    
    - 信号槽: signals_slots/signals_slots.md
    - 发布订阅: subscribe_publish/subscribe_publish.md
    - shell: shell/shell.md

  - 第三方库:
    - ARM-2D: ARM-2D/ARM-2D.md
    - CherryUSB: CherryUSB/CherryUSB.md    
  - About:
    - Overview: about/about.md
    - Team: about/team.md

# 主题配置
theme:
  name: readthedocs  # 使用 readthedocs 主题
  show_powered_by: false  # 隐藏 Powered by Read the Docs 标志

# 额外的 CSS 样式
extra_css:
  - css/custom.css  # 自定义 CSS 样式文件
